### ISSUE TITLE
Parameter to decide which components should be included in the dump

### ISSUE THREAD

**Issue by samugi** [estevaobk/3scaledump#42]
Provide the possibility to pass a parameter in order to decide which of the components (Logs, Secrets, Routes, PVs, ...) should be included, here's an idea:

`chmod style`:
Let's say we have 7 components: A, B, C, D, E, F, G. If we want to fetch all of them we could represent it this way: 
A B C D E F
1 1 1 1 1 1 1
that interpreted as a binary number and converted to decimal would be: 127. 
We could then use the parameter 127 to say we want all the components. Every component except for B would become:
A B C D E F
1 0 1 1 1 1 1 --> 95, etc.

The parameter should default to 127 (all)

**Comment by shannon** [comment]
I think the bit style may be too easy to make mistakes. I would recommend we just use an `--include` and `--exclude` option.

```
--include=dc,logs,secrets
```
Outpus only the dcs, the logs, and the secrets

```
--exclude=logs
```
Outputs everything but the logs

**Comment by estevaobk** [comment]
My suggestion would be something like the below:

`$ 3scale-dump.sh <PROJECT> logs secrets dc`

When nothing other than `<PROJECT>` is specified, fetch everything. Otherwise, just fetch the specific components.

My reason behind it is that when you don't want everything you are already looking for something very specific and hence why I don't think `exclude` would make a huge difference. However if I'm mistaken, the next best option would be Shannon's suggestion =)
