### ISSUE TITLE
Remove the subcompression

### ISSUE THREAD

**Issue by palmieric** [estevaobk/3scaledump#53]
It could be handier if the logs are kept uncompressed in the archive.
As the compression of a compressed archive doesn't reduce much the size (only the header are compressed) it only adds a manual decompression to our steps.

**Comment by estevaobk** [comment]
@palmieric ,

The logs are compressed at the same time they are retrieved in order to mitigate disk space issues on the target environment running it, hence they are compressed on the go, e.g.:

`$ oc logs dc/apicast-staging | gzip -f - > apicast-staging.gz`

This helps to ensure it wouldn't run out of disk space while a log of ~500MB (it could happen sometimes especially for APIcast) is being retrieved before being compressed to something like e.g. ~5MB or less, since it's already retrieved and compressed at the same time as in the example above.

Adding a `.tar` to the file has the purpose of archiving a group of files and directories into a single file instead of compressing them again:
https://unix.stackexchange.com/questions/127169/does-tar-actually-compress-files-or-just-group-them-together

Hence, it doesn't perform a "compression of a compressed archive" as far as I'm aware of as it's just `.tar` and not e.g. `tar.gz`.

Furthermore, there is a handy shell script on the logs folder called `uncompress-logs.sh` which you can just double click and run it, eliminating the need of manually decompressing each log file.

Please let me know whether the above clarifies the subject. I'll keep it open instead of closing it order for us to further discuss it with the team if necessary.

Cheers.

**Comment by estevaobk** [comment]
Closing this out. The format `.tar` is aimed to just group the files but no re-compress them.
